### ISSUE TITLE
Threads are doing similar things multiple times

### ISSUE THREAD

**Issue by tpimh** [zesterer/nilts#3]
On my system there are 4 cores. When I run NILTS, the game lags sometimes and console then shows:
```
[DEBUG] Generated a region
[DEBUG] Generated a region
[DEBUG] Generated a region
[DEBUG] Generated a region
[DEBUG] A region has been unloaded
[DEBUG] A region has been unloaded
[DEBUG] A region has been unloaded
[DEBUG] A region has been unloaded
```
Probably, each should be executed only once.

**Comment by zesterer** [comment]
Nope, it's doing what it should do. It just needs to generate several regions when you move, since each region is 32x32 cells (usually smaller than the window size)
